

create DATABASE ProjectOne
USE ProjectOne

CREATE TABLE ACCOUNT (
  UserID VARCHAR(10) PRIMARY KEY ,
  [Name] NVARCHAR(30),
  Username NVARCHAR(30) UNIQUE,
  [Password] VARCHAR(30),
  PhoneNum VARCHAR(11),
  Email VARCHAR(50)
);

CREATE TABLE [MESSAGE] (
	SenderID VARCHAR(10) FOREIGN KEY REFERENCES ACCOUNT(UserID),
	ReceiverID VARCHAR(10) FOREIGN KEY REFERENCES ACCOUNT(UserID),
	[Time] SMALLDATETIME,
	Contents NVARCHAR(100),
	CONSTRAINT MS_PK PRIMARY KEY(SenderID,ReceiverID)
);

CREATE TABLE BANK (
	BankID VARCHAR(10) PRIMARY KEY,
	BankName VARCHAR(50)
);

CREATE TABLE BANKACCOUNT (
	BankID VARCHAR(10) FOREIGN KEY REFERENCES BANK(BankID),
	UserID VARCHAR(10) FOREIGN KEY REFERENCES ACCOUNT(UserID),
	BankAccount NVARCHAR(20),
	CONSTRAINT BA_PK PRIMARY KEY(BankID,UserID)
);

CREATE TABLE REGION (
	RegionID varchar(10) PRIMARY KEY,
	Region nvarchar(30)
);

CREATE TABLE COUNTRY (
	CountryID varchar(10) PRIMARY KEY,
	RegionID varchar(10) FOREIGN KEY REFERENCES REGION(RegionID),
	Country nvarchar(30)
);

CREATE TABLE [ADDRESS] (
	AddressID varchar(10) PRIMARY KEY,
	CountryID varchar(10) FOREIGN KEY REFERENCES COUNTRY(CountryID),
	[Address] nvarchar(50)
);

CREATE TABLE PLACE (
  PlaceID  VARCHAR(10)  PRIMARY KEY,
  HostID  VARCHAR(10)  FOREIGN KEY REFERENCES ACCOUNT(UserID),
  AddressID VARCHAR(10) FOREIGN KEY REFERENCES [ADDRESS](AddressID),
  Category VARCHAR(20),
  PricePerNight MONEY,
  [Description] NVARCHAR(150),
  Rating NUMERIC(1,1),
  Active BIT
);

CREATE TABLE WITHLIST (
  PlaceID VARCHAR(10)  FOREIGN KEY REFERENCES PLACE(PlaceID),
  UserID VARCHAR(10) FOREIGN KEY REFERENCES ACCOUNT(UserID),
  CONSTRAINT FAV_PK PRIMARY KEY(PlaceID,UserID)
);

CREATE TABLE REVIEW (
  PlaceID VARCHAR(10)  FOREIGN KEY REFERENCES PLACE(PlaceID),
  UserID VARCHAR(10) FOREIGN KEY REFERENCES ACCOUNT(UserID),
  ReviewDate SMALLDATETIME,
  Star NUMERIC(1,1),
  Details NVARCHAR(100),
  CONSTRAINT RV_PK PRIMARY KEY(PlaceID,UserID)
);

CREATE TABLE AMENITIES (
	AmenID VARCHAR(10) PRIMARY KEY,
	[Type] NVARCHAR(20),
	Detail NVARCHAR(50)
);

CREATE TABLE ACCOMMODATION (
  PlaceID  VARCHAR(10)  FOREIGN KEY REFERENCES PLACE(PlaceID),
  AmenID  VARCHAR(10)  FOREIGN KEY REFERENCES AMENITIES(AmenID),
  Condition NVARCHAR(10),
  CONSTRAINT ACCO_PK PRIMARY KEY(PlaceID,AmenID)
);

CREATE TABLE BOOKING (
  BookingID VARCHAR(10)  PRIMARY KEY,
  PlaceID  VARCHAR(10)  FOREIGN KEY REFERENCES PLACE(PlaceID),
  UserID VARCHAR(10) FOREIGN KEY REFERENCES ACCOUNT(UserID),
  Checkin SMALLDATETIME,
  Checkout SMALLDATETIME,
  Guests INT,
  Fee MONEY,
);

CREATE TABLE COUPON (
  CouponID  VARCHAR(10)  PRIMARY KEY,
  PercentOff INT,
  [ExpireDate] SMALLDATETIME
);

CREATE TABLE PAYMENT (
	PaymentID varchar(10) PRIMARY KEY,
	Method varchar(15),
	BankID varchar(10) FOREIGN KEY REFERENCES BANK(BankID)
);

CREATE TABLE [ORDER] (
  OrderID VARCHAR(10)  PRIMARY KEY,
  BookingID  VARCHAR(10)  FOREIGN KEY REFERENCES BOOKING(BookingID),
  CouponID  VARCHAR(10)  FOREIGN KEY REFERENCES COUPON(CouponID),
  TotalPrice MONEY,
  Discount MONEY,
  FinalPrice MONEY,
);













